templateDir: schema 
additionalProperties:
  npmName: restClient
  supportsES6: "true"
  npmVersion: 6.9.0
  withInterfaces: "true"
files:
  modelGeneric.mustache:
    templateType: API 
  apiInner.mustache:
    templateType: API 