# Generated by Django 3.2.7 on 2021-09-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
