# Generated by Django 3.2.6 on 2021-08-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='player',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
