# Generated by Django 4.0.1 on 2022-01-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='season',
            name='locations',
            field=models.ManyToManyField(to='leagues.Location'),
        ),
    ]
